import './globals.css'
import Nav from './nav/Navbar';

export const metadata = {
  title: 'Dutch0x',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#F7F7F7] satoshi-normal">
        <Nav />
        {children}
        </body>
    </html>
  )
}
